### PR TITLE
Suggestion: Information to an error (vagrant)

### PR DESCRIPTION
**Pull request by Ovakefali13**
I got an error starting the vagrant vm and could fix it. 

Maybe this addition to the information section might help someone in the future

Best

### CODE REVIEW

**Comment by Ovakefali13** [comment]
@ajaust How do I fix the last issues for the pipeline?

**Comment by ajaust** [comment]
At the moment we have not found a conclusion yet. After we have fixed https://github.com/Simulation-Software-Engineering/Lecture-Material/issues/32 this should be fine. It is a weird problem with mixing ordered and unordered list.

**Comment by Ovakefali13** [comment]
Alright, thanks, let me know what to change once you figured it out,

**Comment by ajaust** [comment]
If we decide on merging #35 you should be able to solve the problem with the failing pipeline by rebasing. :crossed_fingers:

**Comment by ajaust** [comment]
We have merged #35 into main so you could try rebasing your PR now.

**Comment by Ovakefali13** [comment]
ok, I did the rebase but now it doesn't run the checks anymore

**Comment by Ovakefali13** [comment]
> ok, I did the rebase but now it doesn't run the checks anymore

Never mind, rebase wasn't complete, now it is running checks - but still failing

**Comment by ajaust** [comment]
Did you `git rebase` and afterwards run `git pull`? You seem to have duplicated commits as it seems. It should have been save to use `git push --force` after the rebase since you are the only one working on this PR (as mentioned in the lecture :wink: )

Now it is impossible to do a review because basically all files have changed. Could you try to fix it? Maybe it would be easiest to create a fresh branch from `main`, adding your changes there and then opening a new PR from that branch.

**Comment by Ovakefali13** [comment]
I did `git rebase` and `git pull`, but it told me I need to fix some issues which I did, but I guess this messed up everything. I will create a new branch and PR.

**Comment by Ovakefali13** [comment]
Closed to #42

**Pull request closed without merging**
