### PR TITLE
Move Proxmox VM from Type 1 VMs to Type 2 VMs in `virtualmachines_slides.md`

### PR DESCRIPTION
**Pull request by IshaanDesai**
## Description

Fixes https://github.com/Simulation-Software-Engineering/Lecture-Material/issues/134

## Checklist

- [x] I made sure that the markdown files are formatted properly.
- [x] I made sure that all hyperlinks are working.

### CODE REVIEW

**Comment by IshaanDesai** [comment]
@neumantm correction of #134 done here.

**Comment by neumantm** [comment]
Hm, I think it is easy to mistake Proxmox for a Tye 1 hypervisor due to the fact, that it comes with the OS as one ISO.
Students who know proxmox might get confused here.
It might be better to remove proxmox as an example entirely, to avoid students getting a bad intuition about Type 1 and Type 2 hypervisors.

What do you think?

**Comment by IshaanDesai** [comment]
I do not have a very good idea about the Proxmox VM, but on a high-level look it seems like it is a Type 2 VM. If that is the case, then I will just keep it there for now. Removing it altogether is not the right way to go.

**Comment by neumantm** [comment]
Yes, it is a Type 2 hypervisor, but it is not a good/clear example for one.
Do whatever you see fit, it's your lecture...

**Comment by IshaanDesai** [comment]
Looking at the [features of Proxmox VE](https://www.proxmox.com/en/proxmox-ve/features) I am not convinced that it is fully a Type 2 hypervisor and hence I will keep things as they are for now.

**Pull request closed without merging**
